CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_name VARCHAR(255),
    name VARCHAR(255),
    surname VARCHAR(255),
    date_of_birthday VARCHAR(255),
    email VARCHAR(255),
    phone_number VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
    );
